#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail


REPO_DIR=$(git rev-parse --show-toplevel)
SRC_PATH="$REPO_DIR/exasol_sagemaker_extension"

if [ -a .commit ]
  then
  rm .commit
  git add "$SRC_PATH/resources/"
  git commit --amend -C HEAD --no-verify --allow-empty
fi
exit
