#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

REPO_DIR=$(git rev-parse --show-toplevel)
GITHOOKS_PATH="$REPO_DIR/githooks"
pushd "$REPO_DIR"
bash "$GITHOOKS_PATH/prohibit_commit_to_main.sh"
popd


SRC_PATH="$REPO_DIR/exasol_sagemaker_extension"
pushd "$SRC_PATH/deployment"
python "regenerate_scripts.py"
popd

git add "$SRC_PATH/resources/lua/outputs/"

exit
