name: Build and test project

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install Localstack
        run: pip install localstack=='0.12.18'
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install amalg
          sudo luarocks install lua-cjson
          sudo luarocks install luaunit
          sudo luarocks install mockagne
      - name: Generate sql script
        run: |
          ./scripts/generate_sql_script.sh
      - name: Run Lua unit tests
        run: |
          ./scripts/run_lua_unittests.sh

      - name: Checkout test environment
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..
      - name: Spawn EXASOL environemnt
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 9563 --bucketfs-port-forward 6666 --db-mem-size 4GB
        working-directory: ../integration-test-docker-environment

      - name: Create docker network
        run: docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 it-network
      - name: Run Localstack container
        run: docker run -d  -e SERVICES=s3  -p 4566:4566 -p 4571:4571 --net it-network --ip 192.168.0.2 localstack/localstack
      - name: Add container to the network
        run: docker network connect it-network db_container_test

      - name: Poetry run pytest integration tests
        run: poetry run pytest tests
