name: Build and test project

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    environment: aws

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build Poetry
        run: poetry build

      - name: Install project whl
        run: pip install dist/*.whl

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install --only-deps *.rockspec

      - name: Run Lua unit tests and static code analyzer
        run: poetry run poe lua-tests

      - name: Run unit tests
        run: poetry run pytest tests/unit_tests

      - name: Run integration tests
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run: poetry run pytest --backend=onprem tests/integration_tests
