name: Build and test project

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install amalg
          sudo luarocks install lua-cjson
          sudo luarocks install luaunit
          sudo luarocks install mockagne
          sudo luarocks install exaerror
      - name: Generate sql script
        run: |
          python ./exasol_sagemaker_extension/resources/generate_create_statement_exporting_sql.py
      - name: Run Lua unit tests
        run: |
          ./scripts/run_lua_unittests.sh

      - name: Setup integration test environment
        run: ./scripts/setup_integration_test.sh

      - name: Poetry run pytest integration tests
        run: poetry run pytest tests
