name: Build and test project

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        backend: ["onprem", "saas"]
    runs-on: ubuntu-24.04
    environment: aws
    name: Running ci tests on ${{ matrix.backend }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.6.0
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: '2.1.2'

      - name: Build Poetry
        run: poetry build

      - name: Install project whl
        run: pip install dist/*.whl

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_DEFAULT_REGION: "eu-central-1"
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run: poetry run -- pytest --backend=${{ matrix.backend }} --itde-nameserver="8.8.8.8" tests/ci_tests
