name: Build and test project

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install amalg
          sudo luarocks install lua-cjson
          sudo luarocks install luaunit
          sudo luarocks install mockagne
      - name: Generate sql script
        run: |
          ./scripts/generate_sql_script.sh
      - name: Run Lua unit tests
        run: |
          ./scripts/run_lua_unittests.sh

      - name: Checkout test environment
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..
      - name: Spawn EXASOL environemnt
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 9563 --bucketfs-port-forward 6666 --db-mem-size 4GB
        working-directory: ../integration-test-docker-environment

      - name: Run S3 service on Localstack
        run: docker run --rm -it -e SERVICES=s3  -p 4566:4566 -p 4571:4571 localstack/localstack  &

      - name: Poetry run pytest integration tests
        run: poetry run pytest tests
