name: Build and test project

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    environment: aws

    steps:
      - name: Set pytest markers
        id: pytest-markers
        if: ${{ ! inputs.slow-tests }}
        run: echo slow-tests='-m "not slow"' >> "$GITHUB_OUTPUT"

      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false

      - name: Free disk space by removing large directories
        run: |
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/ghc

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build Poetry
        run: poetry build

      - name: Install project whl
        run: pip install dist/*.whl

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install --only-deps *.rockspec

      - name: Run Lua unit tests and static code analyzer
        run: poetry run poe lua-tests

      - name: Setup integration test environment
        run: ./scripts/setup_integration_test.sh

      - name: Poetry run pytest integration tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_DEFAULT_REGION: "eu-central-1"
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
          PYTEST_ADDOPTS: '${{ steps.pytest-markers.outputs.slow-tests }}'
        run: |
          echo "PYTEST_ADDOPTS = $PYTEST_ADDOPTS"
          poetry run pytest tests
