name: Build and test project

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest
    environment: aws

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install amalg
          sudo luarocks install lua-cjson
          sudo luarocks install luaunit
          sudo luarocks install mockagne
          sudo luarocks install exaerror
          sudo luarocks install luacheck
          sudo luarocks install luacov

      - name: Run Lua unit tests and static code analyzer
        run: poetry run poe lua-tests

      - name: Setup integration test environment
        run: ./scripts/setup_integration_test.sh

      - name: Poetry run pytest integration tests
        run: poetry run pytest tests

      - name: Poetry run pytest ci-tests
        if: "contains(github.event.head_commit.message, '[ci]')"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_DEFAULT_REGION: "eu-central-1"
        run: poetry run pytest tests/ci_tests

