name: Build and test project

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    environment: aws

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build Poetry
        run: poetry build

      - name: Install project whl
        run: pip install dist/*.whl

      - name:  Install Lua dependencies
        if: ${{ ! inputs.slow-tests }}
        run: |
          sudo apt-get install luarocks
          sudo luarocks install --only-deps *.rockspec

      - name: Run Lua unit tests and static code analyzer
        if: ${{ ! inputs.slow-tests }}
        run: poetry run poe lua-tests

      - name: Run unit tests
        if: ${{ ! inputs.slow-tests }}
        run: poetry run pytest tests/unit_tests

      - name: Run integration tests
        if: ${{ ! inputs.slow-tests }}
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run: poetry run pytest --backend=all tests/integration_tests

      - name: Run ci tests
        if: ${{ inputs.slow-tests }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}
          AWS_DEFAULT_REGION: "eu-central-1"
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run: poetry run pytest --backend=all --itde-nameserver="8.8.8.8" tests/ci_tests
