name: Bundle Lua Scripts

on: [ push, pull_request ]

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          fetch-depth: 0

      - name: Install luarocks
        run: sudo apt-get install luarocks

      - name: Install amalg
        run: sudo luarocks install amalg

      - name: Run bundle script file
        run: |
            cd ./lua/src
            chmod +x ./bundle.sh
            ./bundle.sh
        shell: bash

