name: Check documentation build and deployment for feature branch

on:
  push:
    branches-ignore:
      - main
      - github-pages/*

jobs:
  create_github_pages_docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4
    - name: Poetry install
      run: poetry install
    - name: Test documentation deployment for current feature branch
      run: |
        git config --local user.email "opensource@exasol.com"
        git config --local user.name "GitHub Action"
        git fetch
        SOURCE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
        TARGET_BRANCH="$(doc/get_target_branch_name.sh "$SOURCE_BRANCH")"
        poetry run poe push-html-doc-to-github-pages-current || echo
        git push origin --delete "$TARGET_BRANCH"
