name: Check if setup.py is up to date

on: [push]

jobs:
  check_setup_py:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Poetry install
      run: poetry install
    - name: Run packaging update
      run: bash githooks/update_setup_py.sh
    - name: Show changes on working copy
      run: git status --porcelain=v1 -uno
    - name: Show diff on working copy
      run: git diff --cached; cat setup.py
    - name: Check if setup.py changed
      run: |
        [ -z "$(git status --porcelain=v1 -uno 2>/dev/null)" ]
    - name: Check if setup.py works
      run: pip install .
