name: CI Build

on: [ push ]

jobs:
  ci-build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
    runs-on: ubuntu-latest
    environment: aws

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install Poetry
        run: poetry install
      - name: Build Poetry
        run: poetry build
      - name: Install project whl
        run: pip install dist/*.whl

      - name:  Install Lua dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install amalg
          sudo luarocks install lua-cjson
          sudo luarocks install luaunit
          sudo luarocks install mockagne
          sudo luarocks install exaerror
          sudo luarocks install luacheck
          sudo luarocks install luacov

      - name: Checkout test environment
        run: git clone https://github.com/exasol/integration-test-docker-environment.git
        working-directory: ..
      - name: Spawn EXASOL environement
        run: ./start-test-env spawn-test-environment --environment-name test --database-port-forward 9563 --bucketfs-port-forward 6666 --db-mem-size 4GB --nameserver 8.8.8.8
        working-directory: ../integration-test-docker-environment

      - name: Poetry run pytest ci-tests
        run: poetry run pytest tests/ci_tests/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}