name: CI

on:
  pull_request:

jobs:

  ci-job:
    name: Fast Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}

  gate-1:
    name: Gate 1 - Regular CI
    needs: [ ci-job ]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Protection
        run: true

  slow-test-detection:
    name: Run Slow or Expensive Tests?
    runs-on: ubuntu-latest
    steps:
      - name: Detect Slow Tests
        run: true
    environment:
      slow-tests

  run-slow-tests:
    name: Run Slow or Expensive Tests if Requested
    uses: ./.github/workflows/build_slow.yaml
    needs: [ slow-test-detection ]
    secrets: inherit
    with:
      python-version: ${{ matrix.python-version }}

  gate-2:
    name: Gate 2 - Allow Merge
    runs-on: ubuntu-latest
    needs: [ run-slow-tests ]
    steps:
      - name: Branch Protection
        run: true
