name: Generate Sql Script

on: [ push, pull_request ]

jobs:
  generate_sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install luarocks
        run: sudo apt-get install luarocks

      - name: Install amalg
        run: sudo luarocks install amalg

      - name: Generate sql script
        run: ./scripts/generate_sql_script.sh
        shell: bash

