name: Build Language Container

on: [ push ]

jobs:
  integration_tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env

      - name: Build language container
        run: ./build_language_container.sh

      - name: Archive language container
        uses: actions/upload-artifact@v2
        with:
          name: exasol_sagemaker_extension_container
          path: .build_output/cache/exports/*.tar.gz*

      - name: Archive language container build logs
        uses: actions/upload-artifact@v2
        with:
          name: container build logs 
          path: .build_output/jobs/*
