name: Build Language Container

on: [ push ]

jobs:
  integration_tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'poetry'
      - name: Build language container
        run: ./build_language_container.sh
      - name: Archive language container
        uses: actions/upload-artifact@v2
        with:
          name: exasol_sagemaker_extension_container
          path: .build_output/cache/exports/*.tar.gz*
      - name: Archive language container build logs
        uses: actions/upload-artifact@v2
        with:
          name: container build logs 
          path: .build_output/jobs/*
